apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jsonapp
  name: jsonapp
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: jsonapp
  type: NodePort
status:
  loadBalancer: {}
